services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres_password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    configs:
      - source: vector_control
        target: /usr/share/postgresql/17/extension/vector.control

configs:
  vector_control:
    content: |
      comment = 'vector data type and ivfflat and hnsw access methods'
      default_version = '0.8.6'
      module_pathname = '$$libdir/vector'
      relocatable = true
      trusted = true

volumes:
  pg_data:
    driver: local
